			$(function(){
				$("#small")
				.mouseover(function(){
					$(this).attr("src","image/icon/txt_small2.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/icon/txt_small.png");
				});
			});
			$(function(){
				$("#middium")
				.mouseover(function(){
					$(this).attr("src","image/icon/txt_middium2.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/icon/txt_middium.png");
				});
			});
			$(function(){
				$("#large")
				.mouseover(function(){
					$(this).attr("src","image/icon/txt_large2.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/icon/txt_large.png");
				});
			});
			$(function(){
				$("#home_button")
				.mouseover(function(){
					$(this).attr("src","image/navi/on_home_button.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/navi/home_button.png");
				});
			});
			$(function(){
				$("#company_button")
				.mouseover(function(){
					$(this).attr("src","image/navi/on_company_button.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/navi/company_button.png");
				});
			});
			$(function(){
				$("#rent_button")
				.mouseover(function(){
					$(this).attr("src","image/navi/on_rent_button.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/navi/rent_button.png");
				});
			});
			$(function(){
				$("#topics_button")
				.mouseover(function(){
					$(this).attr("src","image/navi/on_topics_button.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/navi/topics_button.png");
				});
			});
			$(function(){
				$("#contact_button")
				.mouseover(function(){
					$(this).attr("src","image/navi/on_contact_button.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/navi/contact_button.png");
				});
			});
			$(function(){
				$(".to_rent img")
				.mouseover(function(){
					$(this).attr("src","image/icon/on_to_rent.png");
				})
				.mouseout(function(){
					$(this).attr("src","image/icon/to_rent.png");
				});
			});
			$("#company dl").corner("8px");
